run:
  concurrency: 6

issues:
  exclude-dirs:
    - .idea
    - .git
    - .run
    - containers
    - migrations
    - postman

linters:
  enable-all: true
  disable:
    - containedctx
    - cyclop
    - depguard
    - execinquery
    - exhaustruct
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - godox
    - gofumpt
    - goimports
    - gomnd
    - gomodguard
    - goprintffuncname
    - ireturn
    - lll
    - nlreturn
    - nonamedreturns
    - paralleltest
    - tagalign
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
