version: "2"

run:
  concurrency: 4
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true

linters:
  default: all
  disable:
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - depguard
    - dogsled
    - exhaustive
    - exhaustruct
    - forbidigo
    - funcorder
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - godox
    - gomodguard
    - goprintffuncname
    - intrange
    - ireturn
    - lll
    - musttag
    - nilnil
    - nlreturn
    - nonamedreturns
    - paralleltest
    - perfsprint
    - tagalign
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: tools/common.go
        text: Use of weak random number generator
      - linters:
          - err113
        path: ((.+)/test/(.+)\.go|(.+)_test\.go)
        text: do not define dynamic errors, use wrapped static errors instead
    paths:
      - .git
      - .idea
      - .run
      - .watchers
      - containers
      - docs
      - graphql
      - migrations
      - proto
      - requests
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(quote)
        - blank
        - dot
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - .git
      - .idea
      - .run
      - .watchers
      - containers
      - docs
      - graphql
      - migrations
      - proto
      - requests
      - third_party$
      - builtin$
      - examples$
