# Parameters doc: https://vektra.github.io/mockery/latest/configuration/#parameter-descriptions
dir: test/mocks
filename: "{{.SrcPackageName}}_{{.InterfaceName | snakecase }}.go"
structname: '{{.SrcPackageName | firstUpper }}{{.InterfaceName}}'
pkgname: mocks
template: testify
force-file-write: true
packages:
  quote/internal/quote:
    interfaces:
      Database: {}
      API: {}
  quote/internal/quoteapi:
    interfaces:
      Database: {}
