version: '3.7'

services:
  backend:
    build:
      context: ..
    container_name: quote-local
    environment:
      SERVER_ADDRESS: "0.0.0.0:1140"
      CORS_MAX_AGE: ${CORS_MAX_AGE}
      SERVER_READ_HEADER_TIMEOUT: ${SERVER_READ_HEADER_TIMEOUT}
      POSTGRES_DSN: "host=db user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB} port=${POSTGRES_PORT} sslmode=disable"
      POSTGRES_MIGRATION_PATH: ${POSTGRES_MIGRATION_PATH}
      RANDOM_QUOTE_CHANCE: ${RANDOM_QUOTE_CHANCE}
    ports:
      - '${SERVER_CONTAINER_PORT}:1140'
    restart: always
