// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type EmptyResult struct {
	Success bool     `json:"success"`
	Errors  []string `json:"errors,omitempty"`
}

type MutationHandler struct {
}

type QueryHandler struct {
}

type Quote struct {
	ID     string   `json:"id"`
	Quote  string   `json:"quote"`
	Author string   `json:"author"`
	Tags   []string `json:"tags,omitempty"`
	Likes  int      `json:"likes"`
}

type QuoteResult struct {
	Success bool     `json:"success"`
	Errors  []string `json:"errors,omitempty"`
	Quote   *Quote   `json:"quote,omitempty"`
}
