// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: quotes.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIDRequest) Reset() {
	*x = UserIDRequest{}
	mi := &file_quotes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIDRequest) ProtoMessage() {}

func (x *UserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quotes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIDRequest.ProtoReflect.Descriptor instead.
func (*UserIDRequest) Descriptor() ([]byte, []int) {
	return file_quotes_proto_rawDescGZIP(), []int{0}
}

func (x *UserIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserAndQuoteIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuoteId       string                 `protobuf:"bytes,2,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAndQuoteIDRequest) Reset() {
	*x = UserAndQuoteIDRequest{}
	mi := &file_quotes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAndQuoteIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAndQuoteIDRequest) ProtoMessage() {}

func (x *UserAndQuoteIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quotes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAndQuoteIDRequest.ProtoReflect.Descriptor instead.
func (*UserAndQuoteIDRequest) Descriptor() ([]byte, []int) {
	return file_quotes_proto_rawDescGZIP(), []int{1}
}

func (x *UserAndQuoteIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserAndQuoteIDRequest) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_quotes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_quotes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_quotes_proto_rawDescGZIP(), []int{2}
}

type Quote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Quote         string                 `protobuf:"bytes,2,opt,name=quote,proto3" json:"quote,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Likes         int64                  `protobuf:"varint,5,opt,name=likes,proto3" json:"likes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quote) Reset() {
	*x = Quote{}
	mi := &file_quotes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quote) ProtoMessage() {}

func (x *Quote) ProtoReflect() protoreflect.Message {
	mi := &file_quotes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quote.ProtoReflect.Descriptor instead.
func (*Quote) Descriptor() ([]byte, []int) {
	return file_quotes_proto_rawDescGZIP(), []int{3}
}

func (x *Quote) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Quote) GetQuote() string {
	if x != nil {
		return x.Quote
	}
	return ""
}

func (x *Quote) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Quote) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Quote) GetLikes() int64 {
	if x != nil {
		return x.Likes
	}
	return 0
}

var File_quotes_proto protoreflect.FileDescriptor

const file_quotes_proto_rawDesc = "" +
	"\n" +
	"\fquotes.proto\"(\n" +
	"\rUserIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"K\n" +
	"\x15UserAndQuoteIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bquote_id\x18\x02 \x01(\tR\aquoteId\"\a\n" +
	"\x05Empty\"o\n" +
	"\x05Quote\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05quote\x18\x02 \x01(\tR\x05quote\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x14\n" +
	"\x05likes\x18\x05 \x01(\x03R\x05likes2\xc3\x01\n" +
	"\x06Quotes\x12\x1d\n" +
	"\tHeartbeat\x12\x06.Empty\x1a\x06.Empty\"\x00\x12+\n" +
	"\x0fGetQuoteHandler\x12\x0e.UserIDRequest\x1a\x06.Quote\"\x00\x127\n" +
	"\x13GetSameQuoteHandler\x12\x16.UserAndQuoteIDRequest\x1a\x06.Quote\"\x00\x124\n" +
	"\x10LikeQuoteHandler\x12\x16.UserAndQuoteIDRequest\x1a\x06.Empty\"\x00B\x17B\vQuotesProtoP\x01Z\x06/protob\x06proto3"

var (
	file_quotes_proto_rawDescOnce sync.Once
	file_quotes_proto_rawDescData []byte
)

func file_quotes_proto_rawDescGZIP() []byte {
	file_quotes_proto_rawDescOnce.Do(func() {
		file_quotes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_quotes_proto_rawDesc), len(file_quotes_proto_rawDesc)))
	})
	return file_quotes_proto_rawDescData
}

var file_quotes_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_quotes_proto_goTypes = []any{
	(*UserIDRequest)(nil),         // 0: UserIDRequest
	(*UserAndQuoteIDRequest)(nil), // 1: UserAndQuoteIDRequest
	(*Empty)(nil),                 // 2: Empty
	(*Quote)(nil),                 // 3: Quote
}
var file_quotes_proto_depIdxs = []int32{
	2, // 0: Quotes.Heartbeat:input_type -> Empty
	0, // 1: Quotes.GetQuoteHandler:input_type -> UserIDRequest
	1, // 2: Quotes.GetSameQuoteHandler:input_type -> UserAndQuoteIDRequest
	1, // 3: Quotes.LikeQuoteHandler:input_type -> UserAndQuoteIDRequest
	2, // 4: Quotes.Heartbeat:output_type -> Empty
	3, // 5: Quotes.GetQuoteHandler:output_type -> Quote
	3, // 6: Quotes.GetSameQuoteHandler:output_type -> Quote
	2, // 7: Quotes.LikeQuoteHandler:output_type -> Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_quotes_proto_init() }
func file_quotes_proto_init() {
	if File_quotes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_quotes_proto_rawDesc), len(file_quotes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_quotes_proto_goTypes,
		DependencyIndexes: file_quotes_proto_depIdxs,
		MessageInfos:      file_quotes_proto_msgTypes,
	}.Build()
	File_quotes_proto = out.File
	file_quotes_proto_goTypes = nil
	file_quotes_proto_depIdxs = nil
}
